title: Dasha Rudy # your name (or website title) here
logo: "/images/2022-02-08 13.58.09.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My portoflio is here
  <br><br>
  <a href="https://www.linkedin.com/in/darya-rudyakova/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
